matrix:
  include:

    # Training Data Project
    - language: java
      jdk: openjdk8  # minimum supported version
      before_script:
        - cd training
        - mvn compile
      script:
        - mvn test

    # C++ Client
    - language: cpp
      compiler: gcc
      # Install CMake 3.0 for Hunter
      addons:
        apt:
          sources:
            - george-edison55-precise-backports
          packages:
            - cmake-data
            - cmake
      before_script:
        - cd clients/cpp
        - cmake CMakeLists.txt
      script:
        - make
        - make test

    # Java Client
    - language: java
      jdk: openjdk7  # minimum supported version
      before_script:
        - cd clients/java
      script:
        - mvn compile
        - mvn test

    # JavaScript Client
    - language: node_js
      node_js:
        - "node"
        - "0.10"  # minimum supported version
      before_script:
        - cd clients/js
        - npm install
      script:
        - npm run test

    # Ruby Client
    - language: ruby
      rvm:
        - 2.0
        - jruby
        - "2.0.0-p0"  # minimum supported version
      before_script:
        - cd clients/ruby
        - gem install bundler
        - bundle install
      script:
        - rake test

    # Ruby Client
    - language: php
      php:
        - 7.0
        - 7.1
        - 7.2
      before_script:
        - cd clients/php
        - composer install
      script:
        - ./vendor/bin/phpunit
